changed

diff --git a/70-appium/71-android-sdk-appium/build/Dockerfile b/70-appium/71-android-sdk-appium/build/Dockerfile
--- a/70-appium/71-android-sdk-appium/build/Dockerfile
+++ b/70-appium/71-android-sdk-appium/build/Dockerfile
@@ -8,7 +8,7 @@ FROM ubuntu:20.04
 
 # Author
 # ---------------------------------------------------------------------- #
-LABEL maintainer "henry.moon"
+LABEL maintainer "thyrlian@gmail.com"
 
 # support multiarch: i386 architecture
 # install Java
@@ -65,10 +65,34 @@ ENV QTWEBENGINE_DISABLE_SANDBOX 1
 ADD license_accepter.sh /opt/
 RUN chmod +x /opt/license_accepter.sh && /opt/license_accepter.sh $ANDROID_SDK_ROOT
 
-
-RUN sdkmanager "platform-tools" "platforms;android-13" "build-tools;31.0.0"
-
 # setup adb server
 EXPOSE 5037
 
-CMD ["/bin/bash"]
+sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"
+
+# install and configure SSH server
+EXPOSE 22
+ADD sshd-banner /etc/ssh/
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends openssh-server supervisor locales && \
+    mkdir -p /var/run/sshd /var/log/supervisord && \
+    locale-gen en en_US en_US.UTF-8 && \
+    apt-get remove -y locales && apt-get autoremove -y && \
+    apt-get clean && rm -rf /var/lib/apt/lists/* && \
+    FILE_SSHD_CONFIG="/etc/ssh/sshd_config" && \
+    echo "\nBanner /etc/ssh/sshd-banner" >> $FILE_SSHD_CONFIG && \
+    echo "\nPermitUserEnvironment=yes" >> $FILE_SSHD_CONFIG && \
+    ssh-keygen -q -N "" -f /root/.ssh/id_rsa && \
+    FILE_SSH_ENV="/root/.ssh/environment" && \
+    touch $FILE_SSH_ENV && chmod 600 $FILE_SSH_ENV && \
+    printenv | grep "JAVA_HOME\|GRADLE_HOME\|KOTLIN_HOME\|ANDROID_SDK_ROOT\|LD_LIBRARY_PATH\|PATH" >> $FILE_SSH_ENV && \
+    echo "\nauth required pam_env.so envfile=$FILE_SSH_ENV" >> /etc/pam.d/sshd && \
+    FILE_AUTH_KEYS="/root/.ssh/authorized_keys" && \
+    touch $FILE_AUTH_KEYS && chmod 600 $FILE_AUTH_KEYS && \
+    for file in /tmp/*.pub; \
+    do if [ -f "$file" ]; then echo "\n" >> $FILE_AUTH_KEYS && cat $file >> $FILE_AUTH_KEYS && echo "\n" >> $FILE_AUTH_KEYS; fi; \
+    done && \
+    (rm /tmp/*.pub 2> /dev/null || true)
+
+ADD supervisord.conf /etc/supervisor/conf.d/
+CMD ["/usr/bin/supervisord"]
